### ISSUE TITLE
Local map I: random tile parameters

### ISSUE THREAD

**Issue by rgripper** [carrot-spillage/kingdom-sim#15]
### Why

A starting point for the RTS part of the game concept. Tile parameters are the foundation for a dynamic environment we could build more complex features: plants, wildlife, natural resources.

### Tasks

 - [ ] Display a tile map that we could iterate to see certain effects to happen
 - [ ] Add a simplex-based generated layer for a parameter
 - [ ] Make multiple parameter layers that I can quickly switch between. They are the 4 tile parameters, with a sum of up to 1.0

### Stats

- Visibility: high
- Complexity: medium-low
