### ISSUE TITLE
Craft tile types based on their soil components

### ISSUE THREAD

**Issue by rgripper** [carrot-spillage/kingdom-sim#16]
### Why

We want to show a player a map that quickly explains them what environment is possible on the tile

### Tasks

- [ ] Gather a list of 10+ kinds of tiles
- [ ] Ask AI to generate colour for each of the tile types
- [ ] Ask AI to map certain components thresholds to tile types
- [ ] Render tiles based on their type

### Issue Stats

- Visibility: high
- Complexity: medium
- Scope creep chance: medium
