### ISSUE TITLE
Create an MVP of logic for tiles properties

### ISSUE THREAD

**Issue by rgripper** [carrot-spillage/kingdom-sim#17]
### Why 

It's a hypothesis that game environmental mechanics can be driven by very basic parameters of the tiles.
Silt does not seem to be of any importance for game mechanic so we remove it for now.
OrganicMatter value seems to be dependent on sand/clay proportion and would not normally form in high-sand/high-clay areas, so should be predicted by those two.
Rocky minerals can play a bigger role, but for now we only use them to signify if the tile is Rocky.

### Tasks
- [x] Remove silt
- [x] Add `other` component. Generate with low-moderate probability of this content in a tile
- [x] Add `fertility` indicator is based on proportion of sand vs clay. Impacted by two factors:
  - The closer it is to 50%/50% sand vs clay the closer the potential indicator to 1.0. 
  - Then scale resulting indicator by % of (clay + sand) vs `other` in overall soil composition.
- [x] Add tile type attribution logic
  - If `sand` is more than 0.5 of the overall contents of soil, we can consider the tile to be Sand.
  - If `other` is more than 0.5 of the overall contents of soil, we can consider the tile to be Rock.
